### ISSUE TITLE
Indentation for multiline variable declarations

### ISSUE THREAD

**Issue by schluete** [mooz/js2-mode#1]
The original version as well as this fork can't handle multiline variable declarations. Currently it indents them like this:

```
var foo = 'bar',
car = 'cdr',
stop = 'start';
```

instead of 

```
var foo = 'bar',
    car = 'cdr',
    stop = 'start';
```

**Comment by Hi-Angel** [comment]
@schluete @mooz hello, this report [has triggered an upstream discussion](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=77803#58) about indentation style. Could you both please clarify: given such JS snippet:

```js
const foo = 'bar',
car = 'cdr',
stop = 'start';
```

How you expect it to be indented? Please note the difference with the report is only `const` instead of `var`.
