### ISSUE TITLE
Declaration warning after named function export

### ISSUE THREAD

**Issue by simenheg** [mooz/js2-mode#215]
Consider the following script:

```js
export function foo () {}

foo();
```

`js2-mode` marks the `foo()` statement with the following warning: "Undeclared variable or function 'foo'".

It seems to me from the [ES6 spec](http://people.mozilla.org/~jorendorff/es6-draft.html#table-42), that the function should also be declared locally. This is also how the [ES6 Module Transpiler](http://esnext.github.io/es6-module-transpiler/) works.

**Comment by dgutov** [comment]
Thanks for the report. There seems to be a conceptual problem here: since `js2-parse-export` simply uses `js2-parse-expr` to parse the function, it gets parsed as `FUNCTION_EXPRESSION` instead of `FUNCTION_STATEMENT`.

And the names of function expressions are only defined within their bodies (#186).

/Cc @cowboyd

**Comment by dgreensp** [comment]
Proposing to fix with PR #287.

**Comment by cowboyd** [comment]
Thanks @dgreensp!

**Comment by simenheg** [comment]
Thanks! That seems to have fixed it.
