### ISSUE TITLE
Setting `js2-include-*-externs` in `.dir-locals.el` has no effect

### ISSUE THREAD

**Issue by JulianKniephoff** [mooz/js2-mode#375]
When you work on different JavaScript projects with mixed environments (say one for the browser, another one with a Node.js environment), you might not want to globally set the `js2-include-*-externs` variables in your Emacs configuration.

One solution normally would be to set them per project in a `.dir-locals.el` file, for example like this:

```elisp
((js2-mode . ((js2-include-node-externs . t))))
```

This does not work however, since these variables only affect `js2-mode`s initialization, apparently, which happens before evaluating the relevant section of the `.dir-locals.el`.

When I first ran into this issue, googling around for a solution brought up [this](https://www.reddit.com/r/emacs/comments/4mzz6q/js2mode_and_dirlocalsel/) thread on reddit, which has some workarounds and also explains the issue nicely. But no one seems to have reported it here, so I went ahead and did it.

If this is not easily fixable, a hint on how to do it right in the documentation for the relevant variables might be a good interim solution, maybe.

**Comment by dgutov** [comment]
The fix is probably not too hard. I see two alternative approaches:

* Include the logic from `js2-set-default-externs` in `js2-highlight-undeclared-vars`.
* Run the code from `js2-set-default-externs` each time at the end of `js2-do-parse` (where `js2-post-parse-callbacks` are run), and alter the value of `js2-additional-externs` instead of `js2-default-externs`.

The variable `js2-default-externs` will go away in either case.

Care to try your hand at it?

**Comment by JulianKniephoff** [comment]
I'll give it a shot. ;)
