### ISSUE TITLE
Error running timer ‘js2-mode-idle-reparse’

### ISSUE THREAD

**Issue by velkyel** [mooz/js2-mode#415]
Create new file foo.js and write
```
a::x()
```

(It's not correct javascript code, I know)

emacs js2-mode throws error:

```
Error running timer ‘js2-mode-idle-reparse’: (wrong-type-argument js2-name-node #s(js2-xml-prop-ref-node 78 0 1 nil #s(js2-expr-stmt-node 133 1 1 nil #s(js2-ast-root 135 1 2 nil nil (#2) nil nil nil nil nil nil 0 nil nil 0 "foo.js" nil nil nil nil) #1) nil nil 3 #s(js2-name-node 39 0 1 nil #1 "a" nil)))
```

and whole emacs became very slow.

Installed version: 20170330.639 (from melpa)

**Comment by dgutov** [comment]
I do see the timer error, but not the slowdown part.

**Comment by shackra** [comment]
I'm experiencing this bug on Emacs 26.1

**Comment by theophilusx** [comment]
I seem to be seeing a very similar issue. Emacs 26.1 latest MELPA packages for js2 etc. The problem is intermittent, but appears to be triggered when typing a template string. Doesn't happen with all template strings and the only fix I have found is to kill the buffer and re-open it. 

Basic symptom is you will start to enter a template string and type something like `${someVar}|` and you will get an error about timers in the minibuffer and all the text within the current block (and following blocks to some undetermined point) will be coloured red i.e. error. Kill the buffer and re-open the file and all is fine until at some point, you type another template string and it happens again. I doesn't happen with all template strings, but does seem to happen more often after a second variable argument i.e. a second ${} element, but that could just b coincidence. 

Tried re-building as suggested in linked thread and that appeared to have solved it initially, but then it just started again. Will attempt to gather a backtrace, but as it is intermittent, this could be difficult. Posted jsut in case it helps others at this time.

**Comment by dgutov** [comment]
Looks like #497 was a duplicate. This seems to work now.

**Comment by dgutov** [comment]
@theophilusx Your problem sounds different. If you can find a stable reproduction scenario, please create a new issue.

Parsing problems are almost always deterministic, so it's a matter of finding the exact buffer contents triggering the problem.

**Comment by theophilusx** [comment]
@dgutov OK, will try to find a recipe to reproduce and if successful will log it. However, have noticed that this issue does seem to have reduced or gone away with recent versions, so maybe fixed.
