### ISSUE TITLE
Switch to lexical binding

### ISSUE THREAD

**Issue by phst** [mooz/js2-mode#426]
Lexical binding should give improved performance and better error reports. When trying to enable lexical binding locally, I've found the following issues (in js2-mode.el at 8a5f492c7ed427a3bdb1125e26a836e582bd2492):

- Line 2370: var-decls and fun-decls are unused. Already has a FIXME; probably just remove entirely. (Actually the whole constructor seems unused and could be removed.)
- Line 7304 references variable `vars`, which is apparently supposed to be dynamically-bound. I'd suggest to pass it as argument instead.
- Line 11102: Argument `pos` is unconditionally overwritten. Probably something should be done with that argument.

**Comment by dgutov** [comment]
Have you tried measuring the performance difference?

**Comment by phst** [comment]
I haven't, but since lexical binding has significant advantages even disregarding performance (more obvious code, better error messages), I'd suggest to just switch.

**Comment by dgutov** [comment]
The code will be pretty much the same, we don't use `lexical-let`.

Last time I tried to measure it, the speed was worse by about the factor of 2. Someone should check the situation these days.

**Comment by phst** [comment]
It seems a bit better, but still bad:

- Dynamic binding: (1.710 ± 0.03) s
- Lexical binding: (2.275 ± 0.04) s

That is, lexical binding is still 33% slower :(

**Comment by dgutov** [comment]
Too bad. But what kind of file did you measure it on?

**Comment by dgutov** [comment]
And did you try the byte-compiled version?

**Comment by phst** [comment]
I think I've just run the unit tests a couple of times. Not sure how representative they are.

**Comment by mishoo** [comment]
I switched to lexical-binding on my branch here: https://github.com/mishoo/js2-mode/tree/devel — so far (coupled with a cleanup which removed unused properties from `js2-scope` nodes) performance seems [consistently better](https://github.com/mooz/js2-mode/pull/474#issuecomment-350456219); not *much* better, but definitely not worse.

**Comment by phst** [comment]
With a recent checkout of js2-mode and an optimized Emacs build from master, I can still reproduce the slowdown with the test suite:

# With dynamic binding

```none
time                 1.860 s    (1.814 s .. 1.924 s)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 1.845 s    (1.834 s .. 1.853 s)
std dev              11.22 ms   (0.0 s .. 12.94 ms)
variance introduced by outliers: 19% (moderately inflated)
```

# With lexical binding

```none
time                 2.649 s    (2.357 s .. 2.874 s)
                     0.999 R²   (0.995 R² .. 1.000 R²)
mean                 2.693 s    (2.627 s .. 2.738 s)
std dev              67.81 ms   (0.0 s .. 78.20 ms)
variance introduced by outliers: 19% (moderately inflated)
```

**Comment by mishoo** [comment]
I did some investigation and I found that `make test` runs on interpreted code.  I can see a lot of reasons why lexical binding is slower in interpreted code, but I hope it's not a case that we should care about.

I updated [my branch](https://github.com/mishoo/js2-mode/tree/devel) so it loads compiled files; check it out — you're in for a surprise.  The difference isn't huge, but lexical binding *is* *faster*, thankfully confirming common sense. ;-)

Just be sure to run `make` first, and time only `make test` (because `make test` will now compile files if needed, and you don't want to add that to the benchmark time).

**Comment by phst** [comment]
Thanks, I can now reproduce this (with a minimal change to load compiled files):

# Dynamic binding

```none
time                 1.261 s    (1.203 s .. 1.337 s)
                     1.000 R²   (0.999 R² .. 1.000 R²)
mean                 1.236 s    (1.211 s .. 1.250 s)
std dev              22.20 ms   (0.0 s .. 24.36 ms)
variance introduced by outliers: 19% (moderately inflated)
```

# Lexical binding

```none
time                 1.113 s    (976.0 ms .. 1.298 s)
                     0.996 R²   (0.995 R² .. 1.000 R²)
mean                 1.178 s    (1.127 s .. 1.211 s)
std dev              50.15 ms   (0.0 s .. 57.91 ms)
variance introduced by outliers: 19% (moderately inflated)
```

While the speedup is not significant (at least in this benchmark) I think it's safe to say that we can switch to lexical binding now.

FYI, here is a post by Stefan where he explains that lexical binding can still be slower in some cases: https://lists.gnu.org/archive/html/emacs-devel/2017-07/msg00052.html

**Comment by dgutov** [comment]
All right guys, thanks for the reminder.

Byte-compiled performance indeed is the most important one, and with `byte-compile--use-old-handlers` defaulting to nil (since Emacs 25.1), it's up to par, and even better. Here's the previous discussion: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=15294#60

The users of Emacs 24 and earlier will see the performance regression, but hey, maybe it's time to upgrade now.
