### ISSUE TITLE
rjsx-mode users should be able to ignore the JSX support warning

### ISSUE THREAD

**Issue by bzalasky** [mooz/js2-mode#532]
When I enable rjsx-mode (after pulling the latest Spacemacs changes in the develop branch and updating packages), a warning buffer is opened up with the following message `Warning (js2-mode): For JSX support, use js-mode with js2-minor-mode.` 

https://github.com/mooz/js2-mode/blob/master/js2-mode.el#L11788

**Comment by dgutov** [comment]
Well, looks like `rjsx-mode` inherits from `js2-jsx-mode`. I didn't expect that.

@felipeochoa I think it should inherit from `js2-mode` and then set up `indent-line-function` as appropriate. Not sure how well it will work with Emacs 27 anyway, though.

/Cc @jacksonrayhamilton

**Comment by bzalasky** [comment]
Thanks for the quick response! I removed the warning from my local copy of js2-mode for now (at work and didn't have time to explore the issue more thoroughly).

**Comment by jacksonrayhamilton** [comment]
Agreed on inheriting from `js2-mode`.  Since `rjsx-mode` defines its own `indent-line-function`, it’s not gaining anything from that inheritance currently, and `js2-jsx-mode` is unlikely to provide useful heritable setup code in the future either.

Since `rjsx-mode`’s indentation is implemented without any reference to Emacs <=26’s `js-jsx-indent-line`, it should continue to work fine.

**Comment by bzalasky** [comment]
I've opened https://github.com/felipeochoa/rjsx-mode/issues/104 to take care of this. Thanks for the suggestion!

**Comment by bzalasky** [comment]
I've submitted a pull request to make this change https://github.com/felipeochoa/rjsx-mode/pull/105.
