### ISSUE TITLE
Missing js2-error face on unknown variable

### ISSUE THREAD

**Issue by DamienCassou** [mooz/js2-mode#568]
I started a fresh Emacs with no configuration, added MELPA, and installed:
-  js2-mode           20201220.1718 installed             Improved JavaScript editing mode

from Melpa. Then, in the scratch buffer, I activated `js2-mode` and typed:

```javascript
describe("foo", () => {});
```

I did a `M-x describe-char` on the first character and got:

![2021-03-30-151900](https://user-images.githubusercontent.com/217543/112995200-47f99800-916b-11eb-9240-39b6a1e0926a.png)

As you can see, there is a `js2-error` overlay but the face is not `js2-error`. As a result, the unknown variable `describe` is not represented as an error. I was expecting "describe" to be in red or similar depending on the theme.

On the contrary the expression below is correctly highlighted as problematic and the font face is `js2-error`:

![2021-03-30-151735](https://user-images.githubusercontent.com/217543/112995004-14b70900-916b-11eb-8b4d-763501161c71.png)

**Comment by DamienCassou** [comment]
This issue was originally reported at https://gitlab.com/protesilaos/modus-themes/-/issues/173.

**Comment by dgutov** [comment]
Hi!

`js2-error` overlay property is present on both error and warning overlays.

The error face denotes parse errors, code that the parser cannot recognize. The first example is not that case: it parses fine, but then fails scope analysis: determination where each function or variable is defined at. Such identifiers are highlighted with the `js2-external-variable` face.

These cases aren't always actual problems because `js2-mode` doesn't necessarily parse all files in the project, so it would be unwise to mark them as errors unconditionally.

**Comment by DamienCassou** [comment]
I understand. Thank you for your answer. Would it make sense to introduce a buffer-local variable to show unknown variables as errors?

**Comment by dgutov** [comment]
Not sure. I don't recall this ever being requested.

If you're sure you need this behavior, how about a PR?

**Comment by DamienCassou** [comment]
If no one cares, I will just close the issue. Thank you for answering.
